import { ref } from 'vue'
import { defineStore } from 'pinia'

export const useProductStore = defineStore('product', () => {
  const initialProducts = [
    // ------------------- Laptops -------------------
    {
      id: 1,
      name: 'MacBook Pro 14"',
      category_id: 1,
      slug: 'macbook-pro-14',
      quantity: 5,
      price: 2000,
      image: 'https://picsum.photos/seed/laptop1/500/300',
      description: 'Apple MacBook Pro 14-inch with M2 chip.',
    },
    {
      id: 2,
      name: 'Dell XPS 13',
      category_id: 1,
      slug: 'dell-xps-13',
      quantity: 8,
      price: 1500,
      image: 'https://picsum.photos/seed/laptop2/500/300',
      description: 'Dell XPS 13, ultra-thin Windows laptop.',
    },
    {
      id: 3,
      name: 'HP Spectre x360',
      category_id: 1,
      slug: 'hp-spectre-x360',
      quantity: 7,
      price: 1400,
      image: 'https://picsum.photos/seed/laptop3/500/300',
      description: 'Convertible 2-in-1 laptop with touchscreen.',
    },
    {
      id: 4,
      name: 'Lenovo ThinkPad X1 Carbon',
      category_id: 1,
      slug: 'lenovo-thinkpad-x1-carbon',
      quantity: 10,
      price: 1600,
      image: 'https://picsum.photos/seed/laptop4/500/300',
      description: 'Business-class laptop with strong performance.',
    },
    {
      id: 5,
      name: 'Asus ZenBook 14',
      category_id: 1,
      slug: 'asus-zenbook-14',
      quantity: 12,
      price: 1200,
      image: 'https://picsum.photos/seed/laptop5/500/300',
      description: 'Slim and portable laptop for daily tasks.',
    },

    // ------------------- Monitors -------------------
    {
      id: 6,
      name: 'Dell UltraSharp 27"',
      category_id: 2,
      slug: 'dell-ultrasharp-27',
      quantity: 15,
      price: 400,
      image: 'https://picsum.photos/seed/monitor1/500/300',
      description: '27-inch 4K UltraSharp monitor.',
    },
    {
      id: 7,
      name: 'LG 34" UltraWide',
      category_id: 2,
      slug: 'lg-ultrawide-34',
      quantity: 6,
      price: 600,
      image: 'https://picsum.photos/seed/monitor2/500/300',
      description: '34-inch UltraWide curved monitor.',
    },
    {
      id: 8,
      name: 'Samsung Odyssey G9',
      category_id: 2,
      slug: 'samsung-odyssey-g9',
      quantity: 3,
      price: 1400,
      image: 'https://picsum.photos/seed/monitor3/500/300',
      description: '49-inch super ultra-wide curved gaming monitor.',
    },
    {
      id: 9,
      name: 'BenQ PD3200U',
      category_id: 2,
      slug: 'benq-pd3200u',
      quantity: 9,
      price: 700,
      image: 'https://picsum.photos/seed/monitor4/500/300',
      description: '32-inch 4K monitor for designers.',
    },
    {
      id: 10,
      name: 'Acer Predator XB273K',
      category_id: 2,
      slug: 'acer-predator-xb273k',
      quantity: 5,
      price: 800,
      image: 'https://picsum.photos/seed/monitor5/500/300',
      description: 'Gaming monitor with G-Sync support.',
    },

    // ------------------- Smart Phones -------------------
    {
      id: 11,
      name: 'iPhone 14 Pro',
      category_id: 3,
      slug: 'iphone-14-pro',
      quantity: 20,
      price: 1200,
      image: 'https://picsum.photos/seed/phone1/500/300',
      description: 'Latest iPhone with Dynamic Island.',
    },
    {
      id: 12,
      name: 'Samsung Galaxy S23',
      category_id: 3,
      slug: 'samsung-galaxy-s23',
      quantity: 18,
      price: 1100,
      image: 'https://picsum.photos/seed/phone2/500/300',
      description: 'High-end Android flagship phone.',
    },
    {
      id: 13,
      name: 'Google Pixel 7 Pro',
      category_id: 3,
      slug: 'google-pixel-7-pro',
      quantity: 12,
      price: 1000,
      image: 'https://picsum.photos/seed/phone3/500/300',
      description: 'Google’s flagship with great camera software.',
    },
    {
      id: 14,
      name: 'OnePlus 11',
      category_id: 3,
      slug: 'oneplus-11',
      quantity: 15,
      price: 900,
      image: 'https://picsum.photos/seed/phone4/500/300',
      description: 'Performance-focused Android phone.',
    },
    {
      id: 15,
      name: 'Xiaomi 13 Pro',
      category_id: 3,
      slug: 'xiaomi-13-pro',
      quantity: 10,
      price: 800,
      image: 'https://picsum.photos/seed/phone5/500/300',
      description: 'Flagship phone with great camera hardware.',
    },

    // ------------------- Cameras -------------------
    {
      id: 16,
      name: 'Canon EOS R5',
      category_id: 4,
      slug: 'canon-eos-r5',
      quantity: 6,
      price: 3900,
      image: 'https://picsum.photos/seed/camera1/500/300',
      description: 'Mirrorless camera with 8K video recording.',
    },
    {
      id: 17,
      name: 'Sony A7 IV',
      category_id: 4,
      slug: 'sony-a7-iv',
      quantity: 9,
      price: 2500,
      image: 'https://picsum.photos/seed/camera2/500/300',
      description: 'Full-frame mirrorless hybrid camera.',
    },
    {
      id: 18,
      name: 'Nikon Z6 II',
      category_id: 4,
      slug: 'nikon-z6-ii',
      quantity: 7,
      price: 2000,
      image: 'https://picsum.photos/seed/camera3/500/300',
      description: 'Mirrorless camera for both photo and video.',
    },
    {
      id: 19,
      name: 'Fujifilm X-T5',
      category_id: 4,
      slug: 'fujifilm-x-t5',
      quantity: 8,
      price: 1800,
      image: 'https://picsum.photos/seed/camera4/500/300',
      description: 'APS-C mirrorless camera with retro design.',
    },
    {
      id: 20,
      name: 'Panasonic Lumix GH6',
      category_id: 4,
      slug: 'panasonic-lumix-gh6',
      quantity: 5,
      price: 2200,
      image: 'https://picsum.photos/seed/camera5/500/300',
      description: 'Micro Four Thirds camera for video creators.',
    },
  ]

  const products = ref(initialProducts)

  return { products }
})
